name: Merge master with gh-pages

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge master with gh-pages
      run: |
        git checkout gh-pages
        git merge master
        git push origin gh-pages
        
